### ISSUE TITLE
为何无法实现UDP透明代理？

### ISSUE THREAD

**Issue by YahuiWong** [Paper-Dragon/docker-transparent-proxy#2]
为何无法实现UDP透明代理？

**Comment by Paper-Dragon** [comment]
你好 @YahuiWong ，
在clash模式下需要您的proxies支持udp流量。
warp模式下会直接接管全部流量，包括udp。
tun2proxy模式下是udp over tcp模式。

都可以接管udp流量，不知道您使用了哪种模式遇到困难？
